// Problem data from liquidslr/interview-company-wise-problems (6-month frequency)
// Top 40 for Amazon, Google, Microsoft, and all 8 for DE Shaw.
const PROBLEMS=[
{t:"Two Sum",d:"Easy",f:100,c:"Amazon",l:"https://leetcode.com/problems/two-sum",tp: "Array"},
{t:"Add Two Numbers",d:"Medium",f:75,c:"Amazon",l:"https://leetcode.com/problems/add-two-numbers",tp: "Array, Hash Table"},
{t:"Longest Substring Without Repeating Characters",d:"Medium",f:88,c:"Amazon",l:"https://leetcode.com/problems/longest-substring-without-repeating-characters",tp: "Binary Tree, Depth-First Search, Hash Table, Sliding Window, String, Tree"},
{t:"Count Good Numbers",d:"Medium",f:25,c:"Amazon",l:"https://leetcode.com/problems/count-good-numbers",tp: "Array, Hash Table"},
{t:"Longest Palindromic Substring",d:"Medium",f:75,c:"Amazon",l:"https://leetcode.com/problems/longest-palindromic-substring",tp: "Binary Tree, Depth-First Search, Hash Table, Sliding Window, String, Tree"},
{t:"Zigzag Conversion",d:"Medium",f:38,c:"Amazon",l:"https://leetcode.com/problems/zigzag-conversion",tp: "Array, Hash Table"},
{t:"Reverse Integer",d:"Medium",f:50,c:"Amazon",l:"https://leetcode.com/problems/reverse-integer",tp: "Array, Hash Table"},
{t:"String to Integer (atoi)",d:"Medium",f:50,c:"Amazon",l:"https://leetcode.com/problems/string-to-integer-atoi",tp: "Hash Table, String"},
{t:"Palindrome Number",d:"Easy",f:62,c:"Amazon",l:"https://leetcode.com/problems/palindrome-number",tp: "Hash Table, String"},
{t:"Regular Expression Matching",d:"Hard",f:50,c:"Amazon",l:"https://leetcode.com/problems/regular-expression-matching",tp: "Array, Hash Table"},
{t:"Container With Most Water",d:"Medium",f:75,c:"Amazon",l:"https://leetcode.com/problems/container-with-most-water",tp: "Array, Hash Table"},
{t:"Integer to Roman",d:"Medium",f:25,c:"Amazon",l:"https://leetcode.com/problems/integer-to-roman",tp: "Array, Hash Table"},
{t:"Roman to Integer",d:"Easy",f:62,c:"Amazon",l:"https://leetcode.com/problems/roman-to-integer",tp: "Array, Hash Table"},
{t:"Longest Common Prefix",d:"Easy",f:75,c:"Amazon",l:"https://leetcode.com/problems/longest-common-prefix",tp: "Array, Hash Table"},
{t:"3Sum",d:"Medium",f:75,c:"Amazon",l:"https://leetcode.com/problems/3sum",tp: "Array"},
{t:"3Sum Closest",d:"Medium",f:38,c:"Amazon",l:"https://leetcode.com/problems/3sum-closest",tp: "Array"},
{t:"Letter Combinations of a Phone Number",d:"Medium",f:62,c:"Amazon",l:"https://leetcode.com/problems/letter-combinations-of-a-phone-number",tp: "Backtracking"},
{t:"4Sum",d:"Medium",f:50,c:"Amazon",l:"https://leetcode.com/problems/4sum",tp: "Array"},
{t:"Remove Nth Node From End of List",d:"Medium",f:38,c:"Amazon",l:"https://leetcode.com/problems/remove-nth-node-from-end-of-list",tp: "Linked List, Two Pointers"},
{t:"Valid Parentheses",d:"Easy",f:75,c:"Amazon",l:"https://leetcode.com/problems/valid-parentheses",tp: "Hash Table, String"},
{t:"Merge Two Sorted Lists",d:"Easy",f:62,c:"Amazon",l:"https://leetcode.com/problems/merge-two-sorted-lists",tp: "Array, Linked List, Sorting, Two Pointers"},
{t:"Generate Parentheses",d:"Medium",f:62,c:"Amazon",l:"https://leetcode.com/problems/generate-parentheses",tp: "Backtracking, Hash Table, String"},
{t:"Merge k Sorted Lists",d:"Hard",f:62,c:"Amazon",l:"https://leetcode.com/problems/merge-k-sorted-lists",tp: "Array, Linked List, Sorting, Two Pointers"},
{t:"Swap Nodes in Pairs",d:"Medium",f:25,c:"Amazon",l:"https://leetcode.com/problems/swap-nodes-in-pairs",tp: "Linked List, Two Pointers"},
{t:"Reverse Nodes in k-Group",d:"Hard",f:50,c:"Amazon",l:"https://leetcode.com/problems/reverse-nodes-in-k-group",tp: "Linked List, Two Pointers"},
{t:"Remove Duplicates from Sorted Array",d:"Easy",f:50,c:"Amazon",l:"https://leetcode.com/problems/remove-duplicates-from-sorted-array",tp: "Array, Sorting"},
{t:"Remove Element",d:"Easy",f:50,c:"Amazon",l:"https://leetcode.com/problems/remove-element",tp: "Array, Hash Table"},
{t:"Find the Index of the First Occurrence in a String",d:"Easy",f:38,c:"Amazon",l:"https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string",tp: "Binary Search, Hash Table, String"},
{t:"Divide Two Integers",d:"Medium",f:25,c:"Amazon",l:"https://leetcode.com/problems/divide-two-integers",tp: "Array, Hash Table"},
{t:"Next Permutation",d:"Medium",f:62,c:"Amazon",l:"https://leetcode.com/problems/next-permutation",tp: "Backtracking"},
{t:"Longest Valid Parentheses",d:"Hard",f:38,c:"Amazon",l:"https://leetcode.com/problems/longest-valid-parentheses",tp: "Hash Table, String"},
{t:"Search in Rotated Sorted Array",d:"Medium",f:62,c:"Amazon",l:"https://leetcode.com/problems/search-in-rotated-sorted-array",tp: "Array, Binary Search, Sorting"},
{t:"Find First and Last Position of Element in Sorted Array",d:"Medium",f:50,c:"Amazon",l:"https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array",tp: "Array, Binary Search, Sorting"},
{t:"Search Insert Position",d:"Easy",f:50,c:"Amazon",l:"https://leetcode.com/problems/search-insert-position",tp: "Binary Search"},
{t:"Valid Sudoku",d:"Medium",f:50,c:"Amazon",l:"https://leetcode.com/problems/valid-sudoku",tp: "Depth-First Search, Matrix"},
{t:"Sudoku Solver",d:"Hard",f:38,c:"Amazon",l:"https://leetcode.com/problems/sudoku-solver",tp: "Depth-First Search, Matrix"},
{t:"Combination Sum",d:"Medium",f:38,c:"Amazon",l:"https://leetcode.com/problems/combination-sum",tp: "Array, Backtracking"},
{t:"Combination Sum II",d:"Medium",f:12,c:"Amazon",l:"https://leetcode.com/problems/combination-sum-ii",tp: "Array, Backtracking"},
{t:"First Missing Positive",d:"Hard",f:62,c:"Amazon",l:"https://leetcode.com/problems/first-missing-positive",tp: "Array, Hash Table"},
{t:"Trapping Rain Water",d:"Hard",f:75,c:"Amazon",l:"https://leetcode.com/problems/trapping-rain-water",tp: "Array, Hash Table"},
{t:"Median of Two Sorted Arrays",d:"Hard",f:75,c:"Google",l:"https://leetcode.com/problems/median-of-two-sorted-arrays",tp: "Array, Sorting"},
{t:"Surrounded Regions",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/surrounded-regions",tp: "Array, Hash Table"},
{t:"Implement Stack using Queues",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/implement-stack-using-queues",tp: "Monotonic Queue, Queue, Stack"},
{t:"Longest Increasing Subsequence",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/longest-increasing-subsequence",tp: "Dynamic Programming"},
{t:"Burst Balloons",d:"Hard",f:25,c:"Google",l:"https://leetcode.com/problems/burst-balloons",tp: "Array, Hash Table"},
{t:"Reverse String",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/reverse-string",tp: "Hash Table, String"},
{t:"Intersection of Two Arrays",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/intersection-of-two-arrays",tp: "Array"},
{t:"First Unique Character in a String",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/first-unique-character-in-a-string",tp: "Hash Table, String"},
{t:"Decode String",d:"Medium",f:62,c:"Google",l:"https://leetcode.com/problems/decode-string",tp: "Dynamic Programming, Hash Table, String"},
{t:"Evaluate Division",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/evaluate-division",tp: "Array, Hash Table"},
{t:"Trapping Rain Water II",d:"Hard",f:25,c:"Google",l:"https://leetcode.com/problems/trapping-rain-water-ii",tp: "Array, Hash Table"},
{t:"Pacific Atlantic Water Flow",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/pacific-atlantic-water-flow",tp: "Array, Hash Table"},
{t:"Meeting Rooms III",d:"Hard",f:25,c:"Google",l:"https://leetcode.com/problems/meeting-rooms-iii",tp: "Heap (Priority Queue), Sorting"},
{t:"Target Sum",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/target-sum",tp: "Array"},
{t:"Subarray Sum Equals K",d:"Medium",f:62,c:"Google",l:"https://leetcode.com/problems/subarray-sum-equals-k",tp: "Array, Sliding Window, String"},
{t:"Big Countries",d:"Easy",f:25,c:"Google",l:"https://leetcode.com/problems/big-countries",tp: "Array, Hash Table"},
{t:"Create Hello World Function",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/create-hello-world-function",tp: "Array, Hash Table"},
{t:"To Be Or Not To Be",d:"Easy",f:12,c:"Google",l:"https://leetcode.com/problems/to-be-or-not-to-be",tp: "Array, Hash Table"},
{t:"Fruit Into Baskets",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/fruit-into-baskets",tp: "Array, Hash Table"},
{t:"Sum of Subarray Minimums",d:"Medium",f:12,c:"Google",l:"https://leetcode.com/problems/sum-of-subarray-minimums",tp: "Array, Sliding Window, String"},
{t:"Recyclable and Low Fat Products",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/recyclable-and-low-fat-products",tp: "Array"},
{t:"Single Number II",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/single-number-ii",tp: "Array, Hash Table"},
{t:"Minimum Falling Path Sum",d:"Medium",f:12,c:"Google",l:"https://leetcode.com/problems/minimum-falling-path-sum",tp: "Array, Depth-First Search, Dynamic Programming, Matrix"},
{t:"Wildcard Matching",d:"Hard",f:38,c:"Google",l:"https://leetcode.com/problems/wildcard-matching",tp: "Array, Hash Table"},
{t:"Insert Interval",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/insert-interval",tp: "Array, Sorting"},
{t:"Length of Last Word",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/length-of-last-word",tp: "Hash Table, String"},
{t:"Permutation Sequence",d:"Hard",f:25,c:"Google",l:"https://leetcode.com/problems/permutation-sequence",tp: "Backtracking"},
{t:"Add Binary",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/add-binary",tp: "Array, Hash Table"},
{t:"Sqrt(x)",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/sqrtx",tp: "Array, Hash Table"},
{t:"Edit Distance",d:"Medium",f:50,c:"Google",l:"https://leetcode.com/problems/edit-distance",tp: "Array, Hash Table"},
{t:"Maximal Rectangle",d:"Hard",f:50,c:"Google",l:"https://leetcode.com/problems/maximal-rectangle",tp: "Stack"},
{t:"Binary Tree Inorder Traversal",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/binary-tree-inorder-traversal",tp: "Binary Tree, Depth-First Search, Tree"},
{t:"Balanced Binary Tree",d:"Easy",f:25,c:"Google",l:"https://leetcode.com/problems/balanced-binary-tree",tp: "Binary Tree, Depth-First Search, Tree"},
{t:"Word Break",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/word-break",tp: "Hash Table, String"},
{t:"Max Points on a Line",d:"Hard",f:12,c:"Google",l:"https://leetcode.com/problems/max-points-on-a-line",tp: "Array, Hash Table"},
{t:"Find Minimum in Rotated Sorted Array",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array",tp: "Array, Binary Search, Sorting"},
{t:"Employees Earning More Than Their Managers",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/employees-earning-more-than-their-managers",tp: "Array, Hash Table"},
{t:"Minimum Size Subarray Sum",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/minimum-size-subarray-sum",tp: "Array, Sliding Window, String"},
{t:"House Robber II",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/house-robber-ii",tp: "Dynamic Programming"},
{t:"Maximal Square",d:"Medium",f:50,c:"Google",l:"https://leetcode.com/problems/maximal-square",tp: "Array, Hash Table"},
{t:"Basic Calculator",d:"Hard",f:38,c:"Google",l:"https://leetcode.com/problems/basic-calculator",tp: "Stack"},
{t:"Kth Smallest Element in a BST",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/kth-smallest-element-in-a-bst",tp: "Binary Tree, Depth-First Search, Heap (Priority Queue), Sorting, Tree"},
{t:"Add Digits",d:"Easy",f:25,c:"Google",l:"https://leetcode.com/problems/add-digits",tp: "Array, Hash Table"},
{t:"Perfect Squares",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/perfect-squares",tp: "Array, Hash Table"},
{t:"Expression Add Operators",d:"Hard",f:12,c:"Google",l:"https://leetcode.com/problems/expression-add-operators",tp: "Array, Hash Table"},
{t:"Coin Change",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/coin-change",tp: "Dynamic Programming"},
{t:"Longest Increasing Path in a Matrix",d:"Hard",f:25,c:"Google",l:"https://leetcode.com/problems/longest-increasing-path-in-a-matrix",tp: "Depth-First Search, Matrix"},
{t:"Add Two Integers",d:"Easy",f:50,c:"Google",l:"https://leetcode.com/problems/add-two-integers",tp: "Array, Hash Table"},
{t:"House Robber III",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/house-robber-iii",tp: "Dynamic Programming"},
{t:"Reverse Vowels of a String",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/reverse-vowels-of-a-string",tp: "Hash Table, String"},
{t:"Top K Frequent Elements",d:"Medium",f:50,c:"Google",l:"https://leetcode.com/problems/top-k-frequent-elements",tp: "Heap (Priority Queue), Sorting"},
{t:"Russian Doll Envelopes",d:"Hard",f:50,c:"Google",l:"https://leetcode.com/problems/russian-doll-envelopes",tp: "Array, Hash Table"},
{t:"Logger Rate Limiter",d:"Easy",f:38,c:"Google",l:"https://leetcode.com/problems/logger-rate-limiter",tp: "Array, Hash Table"},
{t:"Insert Delete GetRandom O(1)",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/insert-delete-getrandom-o1",tp: "Array, Hash Table"},
{t:"Remove K Digits",d:"Medium",f:38,c:"Google",l:"https://leetcode.com/problems/remove-k-digits",tp: "Array, Hash Table"},
{t:"Split Array Largest Sum",d:"Hard",f:50,c:"Google",l:"https://leetcode.com/problems/split-array-largest-sum",tp: "Array"},
{t:"Partition Equal Subset Sum",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/partition-equal-subset-sum",tp: "Array, Backtracking"},
{t:"Longest Repeating Character Replacement",d:"Medium",f:50,c:"Google",l:"https://leetcode.com/problems/longest-repeating-character-replacement",tp: "Array, Hash Table"},
{t:"Find All Anagrams in a String",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/find-all-anagrams-in-a-string",tp: "Binary Search, Hash Table, String"},
{t:"String Compression",d:"Medium",f:25,c:"Google",l:"https://leetcode.com/problems/string-compression",tp: "Hash Table, String"},
{t:"Multiply Strings",d:"Medium",f:38,c:"Microsoft",l:"https://leetcode.com/problems/multiply-strings",tp: "Hash Table, String"},
{t:"Restore IP Addresses",d:"Medium",f:50,c:"Microsoft",l:"https://leetcode.com/problems/restore-ip-addresses",tp: "Array, Hash Table"},
{t:"Best Time to Buy and Sell Stock III",d:"Hard",f:25,c:"Microsoft",l:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii",tp: "Array, Greedy"},
{t:"LFU Cache",d:"Hard",f:38,c:"Microsoft",l:"https://leetcode.com/problems/lfu-cache",tp: "Array, Hash Table"},
{t:"Recover Binary Search Tree",d:"Medium",f:50,c:"Microsoft",l:"https://leetcode.com/problems/recover-binary-search-tree",tp: "Binary Search, Binary Tree, Depth-First Search, Tree"},
{t:"Subarrays with K Different Integers",d:"Hard",f:50,c:"Microsoft",l:"https://leetcode.com/problems/subarrays-with-k-different-integers",tp: "Array, Sliding Window, String"},
{t:"H-Index",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/h-index",tp: "Array, Hash Table"},
{t:"Interleaving String",d:"Medium",f:38,c:"Microsoft",l:"https://leetcode.com/problems/interleaving-string",tp: "Hash Table, String"},
{t:"Ransom Note",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/ransom-note",tp: "Array, Hash Table"},
{t:"Diagonal Traverse",d:"Medium",f:50,c:"Microsoft",l:"https://leetcode.com/problems/diagonal-traverse",tp: "Array, Hash Table"},
{t:"Permutations II",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/permutations-ii",tp: "Backtracking"},
{t:"Longest Substring with At Most K Distinct Characters",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters",tp: "Binary Tree, Depth-First Search, Hash Table, Sliding Window, String, Tree"},
{t:"Valid Parenthesis String",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/valid-parenthesis-string",tp: "Hash Table, String"},
{t:"Online Stock Span",d:"Medium",f:38,c:"Microsoft",l:"https://leetcode.com/problems/online-stock-span",tp: "Array, Hash Table"},
{t:"Number of Visible People in a Queue",d:"Hard",f:25,c:"Microsoft",l:"https://leetcode.com/problems/number-of-visible-people-in-a-queue",tp: "Monotonic Queue, Queue"},
{t:"Maximum Points You Can Obtain from Cards",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards",tp: "Array, Hash Table"},
{t:"Find All Duplicates in an Array",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/find-all-duplicates-in-an-array",tp: "Array, Binary Search"},
{t:"Boundary of Binary Tree",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/boundary-of-binary-tree",tp: "Binary Tree, Depth-First Search, Tree"},
{t:"Minimum Edge Reversals So Every Node Is Reachable",d:"Hard",f:62,c:"Microsoft",l:"https://leetcode.com/problems/minimum-edge-reversals-so-every-node-is-reachable",tp: "Linked List, Two Pointers"},
{t:"Minimum Operations to Reduce an Integer to 0",d:"Medium",f:62,c:"Microsoft",l:"https://leetcode.com/problems/minimum-operations-to-reduce-an-integer-to-0",tp: "Array, Hash Table"},
{t:"Subarray Sums Divisible by K",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/subarray-sums-divisible-by-k",tp: "Array, Sliding Window, String"},
{t:"Minimum Value to Get Positive Step by Step Sum",d:"Easy",f:38,c:"Microsoft",l:"https://leetcode.com/problems/minimum-value-to-get-positive-step-by-step-sum",tp: "Array"},
{t:"Reverse Bits",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/reverse-bits",tp: "Array, Hash Table"},
{t:"Minimum Difficulty of a Job Schedule",d:"Hard",f:50,c:"Microsoft",l:"https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule",tp: "Array, Hash Table"},
{t:"Monthly Transactions I",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/monthly-transactions-i",tp: "Array, Hash Table"},
{t:"Minimum Absolute Difference",d:"Easy",f:38,c:"Microsoft",l:"https://leetcode.com/problems/minimum-absolute-difference",tp: "Array, Hash Table"},
{t:"Customer Who Visited but Did Not Make Any Transactions",d:"Easy",f:50,c:"Microsoft",l:"https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions",tp: "Array, Hash Table"},
{t:"Perfect Number",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/perfect-number",tp: "Array, Hash Table"},
{t:"Design Linked List",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/design-linked-list",tp: "Linked List, Two Pointers"},
{t:"Delete Duplicate Emails",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/delete-duplicate-emails",tp: "Array, Hash Table"},
{t:"Network Delay Time",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/network-delay-time",tp: "Breadth-First Search, Graph"},
{t:"Minimum Knight Moves",d:"Medium",f:25,c:"Microsoft",l:"https://leetcode.com/problems/minimum-knight-moves",tp: "Array, Hash Table"},
{t:"Convert Sorted Array to Binary Search Tree",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree",tp: "Array, Binary Search, Binary Tree, Depth-First Search, Sorting, Tree"},
{t:"Classes With at Least 5 Students",d:"Easy",f:25,c:"Microsoft",l:"https://leetcode.com/problems/classes-with-at-least-5-students",tp: "Array, Hash Table"},
{t:"Implement Trie (Prefix Tree)",d:"Medium",f:38,c:"Microsoft",l:"https://leetcode.com/problems/implement-trie-prefix-tree",tp: "Binary Tree, Depth-First Search, Tree"},
{t:"Best Time to Buy and Sell Stock with Transaction Fee",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee",tp: "Array, Greedy"},
{t:"Time Based Key-Value Store",d:"Medium",f:75,c:"Apple",l:"https://leetcode.com/problems/time-based-key-value-store",tp: "Array, Hash Table"},
{t:"Subarray Product Less Than K",d:"Medium",f:62,c:"Apple",l:"https://leetcode.com/problems/subarray-product-less-than-k",tp: "Array, Sliding Window, String"},
{t:"Remove All Adjacent Duplicates In String",d:"Easy",f:62,c:"Apple",l:"https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string",tp: "Hash Table, String"},
{t:"Distribute Money to Maximum Children",d:"Easy",f:50,c:"Apple",l:"https://leetcode.com/problems/distribute-money-to-maximum-children",tp: "Array, Hash Table"},
{t:"Minimize Maximum Component Cost",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/minimize-maximum-component-cost",tp: "Array, Hash Table"},
{t:"Maximum Path Quality of a Graph",d:"Hard",f:50,c:"Apple",l:"https://leetcode.com/problems/maximum-path-quality-of-a-graph",tp: "Breadth-First Search, Depth-First Search, Graph, Matrix"},
{t:"Short Encoding of Words",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/short-encoding-of-words",tp: "Hash Table, String"},
{t:"Minimum Speed to Arrive on Time",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/minimum-speed-to-arrive-on-time",tp: "Array, Hash Table"},
{t:"Peeking Iterator",d:"Medium",f:50,c:"Apple",l:"https://leetcode.com/problems/peeking-iterator",tp: "Array, Hash Table"},
{t:"Convert Sorted List to Binary Search Tree",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree",tp: "Array, Binary Search, Binary Tree, Depth-First Search, Linked List, Sorting, Tree, Two Pointers"},
{t:"Flatten Nested List Iterator",d:"Medium",f:50,c:"Apple",l:"https://leetcode.com/problems/flatten-nested-list-iterator",tp: "Linked List, Two Pointers"},
{t:"Dot Product of Two Sparse Vectors",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/dot-product-of-two-sparse-vectors",tp: "Array"},
{t:"Best Time to Buy and Sell Stock with Cooldown",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown",tp: "Array, Greedy"},
{t:"My Calendar II",d:"Medium",f:38,c:"Apple",l:"https://leetcode.com/problems/my-calendar-ii",tp: "Array, Hash Table"}
];

// End of PROBLEMS

const HLD_SYSTEMS=[
{n:"URL Shortener",d:"TinyURL — hashing, base62, read-heavy",tags:["Hashing","NoSQL","Cache"]},
{n:"News Feed",d:"Facebook/Twitter — fan-out, ranking",tags:["Fan-out","Cache","MQ"]},
{n:"Chat/Messaging",d:"WhatsApp — WebSocket, delivery guarantees",tags:["WebSocket","MQ","Presence"]},
{n:"Video Streaming",d:"YouTube/Netflix — transcoding, CDN",tags:["CDN","Blob Store","Transcoding"]},
{n:"File Storage",d:"Google Drive/Dropbox — sync, chunking",tags:["Chunking","Sync","Metadata"]},
{n:"Ride Sharing",d:"Uber/Lyft — proximity, matching",tags:["Geospatial","Matching","Real-time"]},
{n:"E-Commerce",d:"Amazon — catalog, cart, orders",tags:["Inventory","Payment","Search"]},
{n:"Search Autocomplete",d:"Google — trie, ranking, prefix",tags:["Trie","Cache","Analytics"]},
{n:"Web Crawler",d:"Google — politeness, dedup, scale",tags:["Queue","DNS","Dedup"]},
{n:"Payment System",d:"Stripe — idempotency, ledger",tags:["Idempotency","Ledger","Retry"]},
{n:"Notification System",d:"Push/Email/SMS — fanout, templates",tags:["MQ","Priority","Template"]},
{n:"Collaborative Editor",d:"Google Docs — CRDT, OT",tags:["CRDT","WebSocket","Versioning"]},
{n:"Rate Limiter",d:"API gateway — token bucket, sliding window",tags:["Token Bucket","Redis","Distributed"]},
{n:"Object Storage",d:"S3 — metadata, replication",tags:["Erasure Coding","Metadata","Replication"]},
{n:"Proximity Service",d:"Yelp — geohash, quadtree",tags:["Geohash","Quadtree","Cache"]},
{n:"Ad Click Aggregation",d:"Real-time analytics — streaming, exactly-once",tags:["Kafka","Flink","Lambda"]},
{n:"Distributed Cache",d:"Memcached/Redis — eviction, consistency",tags:["Consistent Hash","LRU","Replication"]},
{n:"Unique ID Generator",d:"Snowflake — distributed, sortable",tags:["Snowflake","UUID","Clock"]},
{n:"Key-Value Store",d:"DynamoDB — partition, replication",tags:["LSM","Gossip","Quorum"]},
{n:"Monitoring/Alerting",d:"Datadog — time series, alerting",tags:["TSDB","Aggregation","Alert"]},
{n:"Social Graph",d:"LinkedIn — graph DB, connections",tags:["Graph DB","BFS","Cache"]},
{n:"Ticket Booking",d:"BookMyShow — seat locking, concurrency",tags:["Locking","Queue","Payment"]},
{n:"Search Engine",d:"Elasticsearch — inverted index, ranking",tags:["Inverted Index","TF-IDF","Shard"]},
{n:"Food Delivery",d:"DoorDash — dispatch, ETA, tracking",tags:["Geospatial","Dispatch","Tracking"]},
{n:"Cloud IDE",d:"Replit — containers, real-time sync",tags:["Containers","WebSocket","FS"]},
];

const LLD_SYSTEMS=[
{n:"Parking Lot",d:"Vehicle types, spots, ticketing",tags:["Factory","Strategy"]},
{n:"Elevator System",d:"Scheduling, multi-elevator",tags:["State","Observer"]},
{n:"Vending Machine",d:"States, payment, inventory",tags:["State","Strategy"]},
{n:"Library Management",d:"Books, members, reservations",tags:["CRUD","Observer"]},
{n:"Movie Ticket Booking",d:"Seat selection, concurrency",tags:["Observer","Concurrency"]},
{n:"Snake and Ladder",d:"Board game, dice, rules",tags:["Command","Strategy"]},
{n:"Chess Game",d:"Pieces, moves, validation",tags:["Polymorphism","Strategy"]},
{n:"ATM System",d:"Transactions, balance, auth",tags:["State","Chain of Resp"]},
{n:"Splitwise",d:"Expense splitting, settlements",tags:["Strategy","Observer"]},
{n:"Online Shopping",d:"Cart, orders, payment",tags:["Observer","Factory"]},
{n:"Food Delivery",d:"Restaurant, rider, customer",tags:["Strategy","Observer"]},
{n:"Logging Framework",d:"Log levels, handlers, formatters",tags:["Singleton","Observer"]},
{n:"LRU Cache",d:"Eviction policy, O(1) ops",tags:["Data Structure"]},
{n:"Pub-Sub System",d:"Topics, subscribers, delivery",tags:["Observer","MQ"]},
{n:"Car Rental",d:"Vehicles, reservations, billing",tags:["Factory","Strategy"]},
{n:"Meeting Room Scheduler",d:"Rooms, conflicts, intervals",tags:["Interval","Observer"]},
{n:"Tic-Tac-Toe",d:"Board, players, win check",tags:["Strategy","State"]},
{n:"File System",d:"Files, directories, permissions",tags:["Composite","Iterator"]},
{n:"Rate Limiter",d:"Token bucket, sliding window",tags:["Token Bucket","Strategy"]},
{n:"Task Scheduler",d:"Priority, execution, retry",tags:["Priority Queue","Strategy"]},
];

const HLD_CONCEPTS=["Scalability & Load Balancing","Database Design & Sharding","Caching Strategies","Message Queues & Event-Driven","Consistent Hashing","CAP Theorem & Trade-offs","API Design (REST/gRPC)","CDN & Edge Computing","Rate Limiting & Throttling","Monitoring & Observability","Security & Auth","Capacity Estimation"];

const TIMELINE=[
{w:1,phase:"Phase 1",title:"HLD + DSA",focus:"Alex Xu Ch 1-5 + capacity estimation. Start company-tagged random DSA.",daily:"Morning: 3 LC problems (random, timed). Evening: 2 Alex Xu chapters + blueprint practice.",weekend:"Deep HLD practice: design 2 systems from scratch on paper."},
{w:2,phase:"Phase 1",title:"HLD + DSA",focus:"Alex Xu Ch 6-13 + remaining blueprint systems. Continue DSA.",daily:"Morning: 3 LC problems. Evening: Alex Xu chapters + design practice.",weekend:"Design 3 systems from scratch. Review HLD concepts PDF."},
{w:3,phase:"Phase 1",title:"HLD + DSA",focus:"Hello Interview HLD topics. Practice remaining 13 blueprint systems.",daily:"Morning: 3 LC problems. Evening: Hello Interview + blueprint system.",weekend:"Full HLD mock interview. Design systems without references."},
{w:4,phase:"Phase 2",title:"LLD + DSA",focus:"SOLID + 6 design patterns + first 10 LLD systems.",daily:"Morning: 3 LC problems. Evening: 1-2 LLD systems from blueprint.",weekend:"Deep LLD: design + code 4 systems in Python."},
{w:5,phase:"Phase 2",title:"LLD + DSA",focus:"LLD systems L11-L20. DE Shaw CS fundamentals.",daily:"Morning: 3 LC problems. Evening: LLD systems + CS fundamentals.",weekend:"LLD mock practice + remaining systems."},
{w:6,phase:"Phase 2",title:"LLD + DSA",focus:"LLD review + mock. Company-tagged DSA continues.",daily:"Morning: 3 LC problems. Evening: LLD mock + review.",weekend:"2 full LLD mocks. Review all 20 systems."},
{w:7,phase:"Phase 3",title:"Integration",focus:"Mock interviews (DSA+HLD+LLD+Behavioral). Random unseen LC.",daily:"Morning: 3-4 random LC (unseen). Evening: mock interview or behavioral prep.",weekend:"Full mock loop: DSA + HLD + LLD + Behavioral in one day."},
{w:8,phase:"Phase 4",title:"Final Polish",focus:"Skim all PDFs. Light DSA. Rest before interviews.",daily:"Morning: 2 LC mediums. Evening: skim blueprints + behavioral stories.",weekend:"Full mock day. Then rest. Sleep well."},
];

const START_DATE=new Date('2026-05-17');
